name: Continuous Integration
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build-and-test:
    echo Define your CI job steps here
