name: Main Workflow

on:
  push:
    branches:
      - main

jobs:

  learn-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out $default-branch
        uses: actions/checkout@v3

      - name: Run Learn-github-actions
        uses: ./.github/workflows/learn-github-actions.yml


#  cd:
#    needs: [ci]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Run CD
#        uses: ./.github/workflows/cd.yml
