name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run CI
        uses: ./.github/workflows/ci.yml

  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run CD
        uses: ./.github/workflows/cd.yml
